### ISSUE TITLE
Incorrect permissions on configuration binary

### ISSUE THREAD

**Issue by alexkiro** [SpamExperts/cpanel-addon#39]
### Version information

*Controlpanel:* Cpanel v11.68.0.17
*PHP version:* 5.6.30
*Addon version:* 3.0.96559

### Steps to replicate

 1. Install older version
 2. Run update from the interface
 3. Go to Diag page of the addon

### Actual result

In Diag page

```
Configuration binary:
APIPass binary for 32bits has incorrect permissions (0644) instead of 6755.
CRITICAL
APIPass binary for 64bits has incorrect permissions (0644) instead of 6755.
CRITICAL
```

In cPanel logs: 

```
//usr/local/cpanel/logs/error_log:[29-Nov-2017 11:54:56 UTC] PHP Fatal error:  Cannot use object of type stdClass as array in /usr/src/prospamfilter/library/Installer/Installer.php on line 153
```

### Expected result

No errors 

### Other notes

 - N/A

**Comment by Agoodfella** [comment]
Verified that the issue isn't reproducible in the following cases:

1. Update the addon version from command line - client available build update with latest testing build.
2. Update the addon version through the web interface after an older version has been installed.

Also checked the acl permissions before and after the fix has been applied. Everything is in order:

```
data: 
  tokens: 
    prospamfilter: 
      acls: 
        acct-summary: 1
        add-pkg: 1
        add-pkg-ip: 1
        add-pkg-shell: 1
        all: 1
```
